fix(refs T31998): restore setActiveTabId
demos-europe/demosplan-core pull request #1079
Opened 2023-03-27 14:07 UTC by spiess-demos

**Ticket:** https://yaits.demos-deutschland.de/T31998

Somehow the invoking of setActiveTabId got lost
during the refactoring of the component. Anyhow,
here we go again.

### How to review/test
Go to import, craft a manual statement via "Direkteingabe" tab. Submit the form. After reloading the page, the same tab should be selected.

### PR Checklist

- [X] Link all relevant tickets
- [X] Move the tickets on the board accordingly

2023-03-27 15:00 UTC, salisdemos requested changes

2023-03-27 15:45 UTC, spiess-demos commented on client/js/components/procedure/AdministrationImport/AdministrationImport.vue
> +import { checkResponse, dpRpc, hasAnyPermissions } from '@demos-europe/demosplan-utils'
it was merged after code freeze. https://github.com/demos-europe/demosplan-core/commit/f2c1df8f50cd0c51858f6fbb11723a28c5fb36e7

2023-03-28 07:24 UTC, salisdemos approved these changes

2023-03-28 07:24 UTC, salisdemos commented on client/js/components/procedure/AdministrationImport/AdministrationImport.vue
> +import { checkResponse, dpRpc, hasAnyPermissions } from '@demos-europe/demosplan-utils'
Ok. Then we have to be aware that we will run into a merge conflict. But that can probably not be prevented

2023-03-28 08:26 UTC, merged