replace env with parameters
demos-europe/demosplan-core pull request #1136
Opened 2023-04-04 12:09 UTC by shumyachkin

2023-04-04 13:54 UTC, mussbach requested changes
please use lowersnailcase as for all other params. And define a defaultvalue (empty) in parameters_default.yml

2023-04-05 10:01 UTC, mussbach requested changes

2023-04-05 10:01 UTC, mussbach commented on demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
> +    # knpu_oauth2_client settings
You need to define oauth_keycloak_client_id, oauth_keycloak_client_secret, oauth_keycloak_auth_server_url and oauth_keycloak_realm, not the ones defined here

2023-04-17 10:55 UTC, graupnerdemos approved these changes
This looks correct. However, I think this should go to `main` now?

2023-04-17 13:03 UTC, mussbach commented
No, release is fine as we want to test it with the Keycloak in the other environment

2023-04-18 07:38 UTC, mussbach approved these changes
lgtm, thx

2023-04-18 07:38 UTC, merged