Fix(refs:T34308): missing externId
demos-europe/demosplan-core pull request #1872
Opened 2023-08-18 10:18 UTC by elmasdemos

**Ticket:** https://yaits.demos-deutschland.de/T34308

### Description: 

- the externId was missing
- the checkbox and the author name besides the hash in `Ihre eingereichten Stellungnahmen` shall be removed
- the externId shall be placed right besides the hash in both of the tabs `Mitgezeichnete Stellungnahmen` and `Ihre eingereichten Stellungnahmen` so it shall be consistent to each other
- code beautify, attributes order e.c.

### How to review/test
- login as FPA, go to the public detail of a procedure
-> in nav menu select `Mitgezeichnete Stellungnahmen` or `Einreichungen der Institutionen`
-> switch between the tabs

### PR Checklist

- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly

2023-08-18 10:20 UTC, salisdemos commented
> the checkbox and the author name besides the hash in Ihre eingereichten Stellungnahmen shall be removed

why?

2023-08-18 10:21 UTC, salisdemos commented
> login as FPA, go to the public detail of a procedure

You need an `institution coordinator` to test this. ;-)

2023-08-18 10:21 UTC, elmasdemos commented
> > the checkbox and the author name besides the hash in Ihre eingereichten Stellungnahmen shall be removed
> 
> why?

Talked with product owner about this and its in the ticket commented. she said it has no sense there

2023-08-18 13:46 UTC, sakutademos submitted a review, later dismissed
lgtm + works!

2023-08-18 13:53 UTC, salisdemos requested changes

2023-08-18 14:05 UTC, salisdemos requested changes

2023-08-18 14:05 UTC, salisdemos commented on client/js/components/statement/publicStatementLists/DpPublicStatement.vue
> +              :aria-label="`${Translator.trans('statement.map.drawing.show')} ${Translator.trans('statement')}: ${number}`"
since we learned, that number is `0` shouldnt we use `externalId` here too?

2023-08-18 14:05 UTC, salisdemos commented on client/js/components/statement/publicStatementLists/DpPublicStatement.vue
> -
I think we can't remove this. since the component is used in several places and some need to display the users name

2023-08-18 14:05 UTC, salisdemos commented on client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
> -
actually we want to keep the blank lines between the props.

2023-08-18 14:05 UTC, hwiem requested changes

2023-08-18 14:05 UTC, hwiem commented on client/js/components/statement/publicStatementLists/DpPublicStatement.vue
> +        <div class="inline-block">
Removing this affects several templates, and at least in the "Meine Entwürfe" view I'm sure that we want to keep the checkbox.

2023-09-01 14:04 UTC, mussbach commented
@elmasdemos what should happen with this?

2024-03-01 09:14 UTC, elmasdemos commented
The interface from this project isnt shown corretly for example when I would like to do a statement in public detail of a procedure, so I cannot reproduce the case to clear the concerns and fix the bug. Even the side menu for the AT is not shown yet. The interface seems broken locally. I merged release branch in this branch but its still the same. I cannot continue this way, so Im closing it for now

2024-03-01 09:14 UTC, closed without merging