feature : refactor permission base on EWM project
demos-europe/demosplan-core pull request #1983
Opened 2023-09-08 12:22 UTC by jalalifardemos

Description: Remove Some Permissions and add to every projects base on disabled methods in EWM Permission

### Linked PRs (optional)
List other PRs that are somehow connected to this and explain the connection.

- 
-

2023-09-14 09:15 UTC, bakridemos requested changes

2023-09-14 10:05 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
> -     */
done in [47cdefb](https://github.com/demos-europe/demosplan-core/pull/1983/commits/47cdefb5cfa55de5e67251e5ac199e7a714626e7)

2023-09-26 10:13 UTC, bakridemos submitted a review, later dismissed
lgtm, code review only. Test in process

2023-09-26 10:45 UTC, jalalifardemos commented
fixed permissiontest in core [542ed1c](https://github.com/demos-europe/demosplan-core/pull/1983/commits/5f6ded0f715a3fe916b543241718a92e39f39442)

2023-09-26 11:44 UTC, bakridemos approved these changes
permissionsTest is adjusted. Lgtm, code review and tested too ( according to permissionsTests, all tests results are same as main)

2023-09-28 09:58 UTC, merged