chore (refs T34979): add missing props, when editor used dpUploadModal.
demos-europe/demosplan-core pull request #2132
Opened 2023-10-11 08:32 UTC by ahmad-demos

https://yaits.demos-deutschland.de/T34979
https://github.com/demos-europe/demosplan-ui/pull/567
https://github.com/demos-europe/demosplan-ui/pull/567/commits/2fc10b706e8b427d0a2e8ff420e209799380f9b7

- add missing props, when editor used dpUploadModal.

2023-10-12 06:12 UTC, gruenbergerdemos requested changes
Since you're already here, could you sort the props alphabetically? Except `id`, `ref` and `v-model`, these should stay on top in this order: `id`, `ref`, `v-model` (for correct order also see https://eslint.vuejs.org/rules/attributes-order.html).

2023-10-12 09:29 UTC, spiess-demos commented
From the PR description, i do not understand why these changes are needed.

2023-10-12 09:32 UTC, ahmad-demos commented
> From the PR description, i do not understand why these changes are needed.

because when Editor used `imageButton`, then we need `DpUploadModal & DpUploadFiles`, like `getFileByHash`
https://github.com/demos-europe/demosplan-ui/pull/567/commits/2fc10b706e8b427d0a2e8ff420e209799380f9b7

2023-10-16 09:14 UTC, salisdemos approved these changes

2023-10-19 06:25 UTC, gruenbergerdemos approved these changes

2023-10-19 07:05 UTC, merged