fix: fix phpunit test after refactoring
demos-europe/demosplan-core pull request #2679
Opened 2024-02-02 08:39 UTC by dresslerdemos

The concept of `PropertyDefinition`s and `IncludeDefinition`s was previously improved on in the corresponding dependency and these types deleted. This warrants a couple of adjustments in the `DynamicTransformerTest`.

As it is untested, this PR may only go the famous first 80% currently. But the adjustments may already be sufficient and the test work now.

### How to review/test

### Linked PRs (optional)

### Tasks (optional)

### PR Checklist

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [ ] Link all relevant tickets
- [ ] Move the tickets on the board accordingly

2024-02-02 09:02 UTC, mussbach requested changes
The CI does its duty. The initial error is fixed, tests still fail https://conti.demos-europe.eu/blue/organizations/jenkins/demosplan-core/detail/PR-2679/2/pipeline Could this be handled in this PR?

2024-02-05 18:42 UTC, dresslerdemos commented
Current state: multiple errors in the test were fixed. For further fixing I need to enable debugging in my local test execution again.

2024-05-13 05:55 UTC, mussbach commented
@dresslerdemos what is the expected result when `''` is passed into `testProcedureIncludesWithWarning`? How should it fail?As the DynamicTransformer uses `Assert::stringNotEmpty($requestedInclude)` I think the mock is invalid, wdyt? I would really like to get this merged to fix the ci

2025-01-30 10:56 UTC, sierrazamudiodemos commented
@mussbach I removed the empty string on the data provider. 12 tests passed and 7 are ignored. what about merging like this? I will check the ignored tests in another PR

2025-01-30 11:06 UTC, merged