f (refs ADO-16632): make docxImporter available in addons.
demos-europe/demosplan-core pull request #3226
Opened 2024-06-06 17:13 UTC by MoritzMandler

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/16632

Description:
Make the docxImporter docx-To-HTML available in addons.

### How to review/test
run: ```composer u demos-europe/demosplan-addon```

### Linked PRs (optional)
https://github.com/demos-europe/demosplan-addon/pull/115

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [ ] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

2024-06-07 13:57 UTC, mussbach requested changes
some early minor remarks

2024-06-07 13:57 UTC, mussbach commented on composer.json
> +        "demos-europe/demosplan-addon": "dev-f_ADO_15514_docxAddonImporterInterface",
needs to be adjusted in final version, ok for now

2024-06-07 13:57 UTC, mussbach commented on tests/backend/core/Import/DocxImportToolTest.php
> +        $filePath = __DIR__ . '/MoritzTollesAnschreiben.docx';
no user specific data please

2024-06-11 10:52 UTC, MoritzMandler commented
not needed for the chosen plan.

2024-06-11 10:52 UTC, closed without merging