refactor: unify loading addons
demos-europe/demosplan-core pull request #3261
Opened 2024-06-12 15:28 UTC by salisdemos

To have one single source of truth i use the loadAddonComponents-Method in AddonWrapper instead of calling the RPC-Route directly.

Additionally I removed some dead code, where the addonWrapper was imported, but no in use

2024-06-13 08:33 UTC, spiess-demos requested changes
In the administration dashboard, i get the error:

`TypeError: Cannot read properties of undefined (reading 'default')
    at eval (AddonWrapper.vue?./node_modules/vue-loader/lib/index.js??vue-loader-options!./node_modules/source-map-loader/dist/cjs.js:47:71)`

2024-06-14 16:14 UTC, salisdemos commented on client/js/components/addon/AddonWrapper.vue
> +      loadAddonComponents(this.hookName)
While moving this. I recognized, that we should allow that multiple addons can not only be loaded, but also displayed for one hook:
eb86e59f64501e8652136b8397222e50fe99d45e

2024-06-17 10:55 UTC, spiess-demos commented on client/js/components/addon/AddonWrapper.vue
> +      loadAddonComponents(this.hookName)
if multiple components are loaded within this wrapper, the `refComponent` will be set to all of them with the same value.

2024-06-17 12:05 UTC, salisdemos commented on client/js/components/addon/AddonWrapper.vue
> +      loadAddonComponents(this.hookName)
Since I couldn't find any usage for the refComponent-Prop I simply changed it like so b4ab447d849d9abac7c1c7b866833534526a79a2

2024-06-17 13:30 UTC, spiess-demos approved these changes
lgtm + works!

2024-06-17 13:31 UTC, merged