F dplan163 statement status
demos-europe/demosplan-core pull request #3402
Opened 2024-07-10 10:01 UTC by jalalifardemos

### Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-163/5-3-Als-Fachplanerin-mochte-ich-schnell-einsehen-konnen-in-welchem-Gesamtbearbeitungsstatus-eine-Stellungnahme-sich-befindet-um

Description: 
- create a new column (solved) for placee entity
- two migration to update place table and create a view
- method to update view
- update StatementResourceType.php to show right status

### Linked PRs (optional)
List other PRs that are somehow connected to this and explain the connection. Don't
link private repositories in public ones, but the other way around is fine.

- https://github.com/demos-europe/demosplan-addon/pull/121
- Other PR2 #{PR-number2}

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

2024-07-12 09:12 UTC, salisdemos commented on client/js/components/procedure/admin/AdministrationPlaces.vue
> +
```suggestion
```

2024-07-12 09:33 UTC, salisdemos submitted a review, later dismissed

2024-07-12 09:33 UTC, salisdemos commented on client/js/components/statement/listStatements/ListStatements.vue
> +import StatusBadge from '../../procedure/Shared/StatusBadge.vue'
```suggestion
import StatusBadge from '@DpJs/components/procedure/Shared/StatusBadge.vue'
```

2024-07-12 09:33 UTC, salisdemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
> +                }
I think it has to be like so:
```suggestion
                if ($statement->isAlreadySegmented()) {
                    $segments = $statement->getSegmentsOfStatement();
                    foreach ($segments as $segment) {
                        if (!$segment->getPlace()->getSolved()) {
                            return 'processing';
                        }
                    }
                   
                    return 'completed';
                }
```

2024-07-12 09:33 UTC, salisdemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
> +                    }
Maybe something to clarify what happens (nor sure if the syntax is correct):
```
$unssolvedSegements = array_filter($segements, function($key, $segment) {
    return !$segment->getPlace()->getSolved()
}, ARRAY_FILTER_USE_BOTH));));

if ($unssolvedSegements.length > 0) {
  return 'processing'
} else {
  return 'completed'
}
```

2024-07-12 09:33 UTC, salisdemos commented on demosplan/DemosPlanCoreBundle/Logic/ProcedureStatisticsService.php
> +                            ->andWhere('place.solved = 1')
is there a "andWhereAll"? If so I think that has to be used.

2024-07-12 09:33 UTC, salisdemos commented on demosplan/DemosPlanCoreBundle/Logic/ProcedureStatisticsService.php
> +                        ->andWhere('place.solved = 0')
is there  andWhereAny?
If so, shouldn't it be something like 
```suggestion
                    ->notIn('s.id', $segmentQuery
                        ->andWhereAny('place.solved = 1')
```

2024-07-12 09:33 UTC, salisdemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
> +                if ($statement->isAlreadySegmented()) {
I thought we wanted to move that logic to a centralized place, that it can be used by the RPC-request too?!?

2024-07-12 11:23 UTC, hwiem reviewed
I get this error
```
Attempted to load interface "ViewStatementStatusInterface" from namespace "DemosEurope\DemosplanAddon\Contracts\Entities".
Did you forget a "use" statement for another namespace?
```
when trying to test it locally

2024-07-15 07:06 UTC, bakridemos requested changes

2024-07-15 07:06 UTC, bakridemos commented on demosplan/DemosPlanCoreBundle/Entity/Statement/ViewStatementStatus.php
> +    private string $statement;
i'm not sure if i understand this. this is the status id right? i mean if we need the statement id (what make sense) than it has to be an extra property and may be unique too

2024-07-15 08:57 UTC, jalalifardemos commented
All things about resourcetype is now in https://github.com/demos-europe/demosplan-core/pull/3417.
ViewStatementStatus is be removed

2024-07-18 12:43 UTC, salisdemos commented
> @[jalalifardemos](https://github.com/jalalifardemos) jalalifardemos mentioned this pull request [last week](https://github.com/demos-europe/demosplan-core/pull/3402#ref-pullrequest-2405377892)
> https://github.com/demos-europe/demosplan-core/pull/3417
>  Merged

Now You did, what I wanted to prevent. We got the already reviewed changed from #3417 within this PR. If someone now is reviewing the PR he/she will automatically review the code from the other PR again.

2024-07-19 09:05 UTC, sierrazamudiodemos approved these changes
lgtm

2024-07-19 09:53 UTC, salisdemos commented
> I get this error
> 
> ```
> Attempted to load interface "ViewStatementStatusInterface" from namespace "DemosEurope\DemosplanAddon\Contracts\Entities".
> Did you forget a "use" statement for another namespace?
> ```
> 
> when trying to test it locally

Should be fixed with [2c3ab7d](https://github.com/demos-europe/demosplan-core/pull/3402/commits/2c3ab7d17b597adf3a84f625490b106b299d6e20)

Before You had to update demosplan-addon manually..

2024-07-19 11:47 UTC, hwiem approved these changes
Just a nitpick; FE code lgtm

2024-07-19 11:47 UTC, hwiem commented on tests/frontend/unit/StatusBadge.spec.js
> +  it('renders correctly for each status', () => {
Not a blocker: I think it is better to create an 'it' statement for each test case. That way, if it fails, you know instantly what is broken. If all test cases are in a single test, and the test fails, any of the test cases may be broken.

2024-07-19 12:02 UTC, merged