feature (ref DPLAN163):
demos-europe/demosplan-core pull request #3417
Opened 2024-07-12 11:39 UTC by jalalifardemos

### Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-163/5-3-Als-Fachplanerin-mochte-ich-schnell-einsehen-konnen-in-welchem-Gesamtbearbeitungsstatus-eine-Stellungnahme-sich-befindet-um

Description: 
- create methods for statistics in StatementService.php
- use these methods in ProcedureStatisticsRpcController.php and StatementResourceType.php

### Linked PRs (optional)
List other PRs that are somehow connected to this and explain the connection. Don't
link private repositories in public ones, but the other way around is fine.

- https://github.com/demos-europe/demosplan-core/pull/3402

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

2024-07-15 08:06 UTC, sierrazamudiodemos requested changes

2024-07-15 08:10 UTC, sierrazamudiodemos commented
I think the method where the stn status is calculated looks good! I added some comments

2024-07-15 08:37 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
> +            'new'        => 0,
done in [1d00b0d](https://github.com/demos-europe/demosplan-core/pull/3417/commits/1d00b0dad8fba8200a1bd539c85574fc8d3dec49)

2024-07-15 08:37 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
> +                $this->statementService->computetStatementStatus($statement);
done in [1d00b0d](https://github.com/demos-europe/demosplan-core/pull/3417/commits/1d00b0dad8fba8200a1bd539c85574fc8d3dec49)

2024-07-16 09:33 UTC, salisdemos requested changes

2024-07-16 09:41 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
> +                $this->statementService->getProcessintStatus($statement);
done in [0f0ae42](https://github.com/demos-europe/demosplan-core/pull/3417/commits/0f0ae4240bb9817e433bd32b5256855d06d0bc14)

2024-07-16 09:42 UTC, salisdemos approved these changes

2024-07-16 11:28 UTC, sierrazamudiodemos approved these changes
thanks!

2024-07-16 11:28 UTC, merged