bug(refs DPLAN-12154): Fix segmentation buttons
demos-europe/demosplan-core pull request #3496
Opened 2024-07-29 05:29 UTC by gruenbergerdemos

### Ticket
DPLAN-12154

Move condition for addon rendering addon component from inside the addon to here, so we don't have an empty div lingering around.

### How to review/test

### PR Checklist

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [ ] Link all relevant tickets
- [ ] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

2024-07-29 07:09 UTC, salisdemos commented
> does it make sense to have this condition in core? Or should this logic remain in the addon?

I think I should remain in the addon. The concept about the addon-wrapper is, that any addon could hook into it. So it will happen that other addons like to use the same wrapper (in different configurations) wich quite likely will follow other conditions.

2024-07-29 08:24 UTC, salisdemos requested changes
see comment

2024-07-29 09:37 UTC, graupnerdemos requested changes

2024-07-29 09:37 UTC, graupnerdemos commented on client/js/components/statement/splitStatement/CardPaneCard.vue
> +      v-if="segment.status !== 'confirmed'"
This would mean addon mounting here is only ever allowed for non-confirmed segments. Is this what we want?

2024-07-29 11:23 UTC, graupnerdemos submitted a review, later dismissed

2024-07-30 07:13 UTC, salisdemos approved these changes

2024-07-30 07:21 UTC, merged