F dplan 12268 check if password exists before reset
demos-europe/demosplan-core pull request #3560
Opened 2024-08-14 10:35 UTC by bakridemos

### Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12268/BLP-Prod-Nicht-verifizierte-Nutzer-konnen-sich-bei-BLP-einloggen

Description: check if password exists before reset

Delete the checkbox if it doesn't apply/isn't necessary.

- [X] Link all relevant tickets
- [X] Move the tickets on the board accordingly

2024-08-14 10:58 UTC, MoritzMandler approved these changes
lgtm - tested together - works fine :)

2024-08-15 07:10 UTC, graupnerdemos requested changes

2024-08-15 07:31 UTC, bakridemos commented on demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
> +                    $this->messageBag->add('warning', 'Ihre Email oder Passwort ist inkorrekt');
done in https://github.com/demos-europe/demosplan-core/pull/3560/commits/bf7cf951c8b57e6adc6c8c053934eb0ff22f6811

2024-08-15 08:45 UTC, graupnerdemos approved these changes

2024-08-16 06:59 UTC, merged