fix(DPLAN-1881): add styling to statement fieldsets list
demos-europe/demosplan-core pull request #3576
Opened 2024-08-20 10:44 UTC by sakutademos

### Ticket
[DPLAN-1881]([url](https://demoseurope.youtrack.cloud/issue/DPLAN-1881/Fehlende-Formatierung-fur-Aufzahlungen-und-nummerierte-Listen-in-der-Uberprufungsansicht))

Description: This PR adds styling to the statements fieldsets list and overrides the global none styling for `ul` and `ol` tags.

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly
- [ ] Data-Cy attributes added/updated ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))

2024-08-22 09:17 UTC, spiess-demos requested changes
In other places we use the [.c-styled-html](https://github.com/demos-europe/demosplan-core/blob/b436e48166920d6dd82016a4c75d93d208770b12/demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_styled-html.scss#L18) class. You could tweak that responsibly.

2024-08-27 10:15 UTC, spiess-demos requested changes

2024-08-27 17:18 UTC, sakutademos commented on templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faqlist.html.twig
> +            <div id="scFaq" class="{{ 'layout__item u-1-of-1 u-3-of-4-lap-up u-pl-0 c-styled-html'|prefixClass }}">
done here https://github.com/demos-europe/demosplan-core/pull/3576/commits/249bcdb2fc64cbd7ed78eb271a7e802004061797

2024-08-27 17:18 UTC, sakutademos commented on templates/bundles/DemosPlanCoreBundle/DemosPlanNews/newsdetail.html.twig
>                  <p>{{ news.text|wysiwyg }}</p>
done https://github.com/demos-europe/demosplan-core/pull/3576/commits/249bcdb2fc64cbd7ed78eb271a7e802004061797

2024-08-27 17:18 UTC, sakutademos commented on templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
> +    <div class="layout--flush bg-color--white o-page__padded u-mb c-styled-html">
done https://github.com/demos-europe/demosplan-core/pull/3576/commits/249bcdb2fc64cbd7ed78eb271a7e802004061797

2024-08-28 09:38 UTC, spiess-demos approved these changes
Lgtm!

2024-08-28 11:50 UTC, merged