fix: Ignore cachesum changes on yarn install
demos-europe/demosplan-core pull request #3597
Opened 2024-08-27 11:15 UTC by salisdemos

for some dependencies (vuex-json-api) the cachesum somehow is not stable. It be be related to the fact, that we get the package straight from GH.

2024-08-27 11:20 UTC, hwiem reviewed
Why do we link to a commit of vuex-json-api in the `package.json` instead of releasing a new version?

2024-08-27 11:23 UTC, salisdemos commented
> Why do we link to a commit of vuex-json-api in the `package.json` instead of releasing a new version?

Good question. Ask the maintainer ;-) 
But even if we release now vuex-json-api. We will run into similar issues sooner or later i think

2024-08-27 13:55 UTC, graupnerdemos requested changes
As we discovered, we're using the hash because the dependency branch in question got lost in PR-ization. Maintainer and branch author are wondering how that happened. For now, there should be no need to add this change, if and when we encounter such an issue again, we can re-evaluate making the change. It should however in my opinion always be a temporary solution.

2024-09-09 06:47 UTC, closed without merging

2024-09-09 06:47 UTC, salisdemos commented
not the right approach