fix(DPLAN-2825): layout issue: orga street number is positioned too far to the right
demos-europe/demosplan-core pull request #3790
Opened 2024-10-07 12:57 UTC by sakutademos

### Ticket
[DPLAN-2825](https://demoseurope.youtrack.cloud/issue/DPLAN-2825/Hausnummer-ist-weit-ins-Abseits-geraten)

**Description:** This PR fixes an issue with the layout of the address in the orga data entry: remove `flex-grow `from the street name input to resolve the issue, but some adjustments need to be done: to ensure the input displays its value without being cut off, the size of the input should be set to match the street name length. Otherwise, if flex-grow is not set, the input may be cropped.

Since the Blp project has a different design compared to Bobsh, Plafest, and Diplanfest (where inputs have borders), it makes sense to keep the design for Blp unchanged.

### How to review/test
Login -> Usermenu -> auf Organamen klicken

affects: Bobsh, Bobhh, Plansfest, DiPlanfest und Blp

2024-10-08 06:55 UTC, sakutademos commented
also, a question: does it make sense to create a Vue component for it instead of Twig?

2024-10-08 06:59 UTC, salisdemos commented
> also, a question: does it make sense to create a Vue component for it instead of Twig?

absolute

2024-10-08 07:00 UTC, salisdemos commented
please be aware of not using project names within core PRs :pray: . Please use generalized wordings instead

2024-10-17 09:06 UTC, salisdemos requested changes
Looks like something is a bit messed up. I see quite a bunch of changes, that look like they don't belong here. (like package.json Dockerfile, ...)

2025-04-30 10:05 UTC, closed without merging