chore: Use flat option for esLint
demos-europe/demosplan-core pull request #4109
Opened 2024-12-04 07:11 UTC by salisdemos

since esLint 9 they restructured the config file to a "flat" way.
And eslintrc.js is replaced by eslint.config.js

By now its not working properly.

The linter itself runs, but when building the fe-assets, some error occurs.
And I'm still investigating if the ide uses the new configfile

2024-12-06 07:25 UTC, hwiem requested changes
Thanks for setting this up :heart: 
It works and looks good, but I'd like to keep the rules defined in https://github.com/standard/standard/blob/master/RULES.md. If I remember correctly, stylisticJs can be used for this (see https://github.com/demos-europe/planningcloud-hub/blob/main/eslint.config.js). 

In general I think we should try to have a base eslint config for all projects to keep things consistent (see https://github.com/spiess-demos/eslint-config-demos/blob/main/eslint.config.js),  which of course isn't something to solve in this PR, but maybe to keep in mind.

2025-02-14 07:23 UTC, mussbach commented
@salisdemos what should happen with this PR?

2025-02-17 07:45 UTC, salisdemos commented
> @salisdemos what should happen with this PR? I tried to fix the reviewdog eslint task and stumbled over this.

Its on my list of PRs that will be focused after the vue3-PR is merged

2025-08-22 11:21 UTC, hwiem commented
Replaced by https://github.com/demos-europe/demosplan-core/pull/5102 to have a common remote branch

2025-08-22 11:21 UTC, closed without merging