F dplan 12013 #2 topical tags
demos-europe/demosplan-core pull request #4134
Opened 2024-12-11 12:47 UTC by MoritzMandler

### Ticket
DPLAN-XXXXX
or
https://www.dev.diplanung.de/DefaultCollection/EfA%20DiPlanung/_workitems/edit/XXXXX

### How to review/test

### PR Checklist

- [ ] Create/Update tests
- [ ] Update documentation
- [ ] Add/Update data-cy attributes ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))
- [ ] Run `yarn lint`
- [ ] Run `yarn test`
- [ ] Link all relevant tickets
- [ ] Move the tickets on the board accordingly

2025-01-24 14:27 UTC, breierDemos reviewed
Pretty big, only looked at it a little. Maybe I'll look at it again later when I have more time.

2025-01-24 14:27 UTC, breierDemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
> +            ['topic', 'procedure', 'id']
You can use the Paths class like this.
`Paths::tag()->topic->procedure->id`

2025-01-27 12:57 UTC, sakutademos commented on client/js/components/tags/TagsList.vue
> +      const newParent = !this.TagTopic[parentId].relationships.tags.data.find(tag => tag.id === elementId)
if it is a boolean value, it could be named smth like `isNewParent` for the better readability

2025-01-27 12:57 UTC, sakutademos commented on client/js/store/core/initStore.js
> +                  response = await success.json()
I am not sure if it is correct so, as I receive warnings in the console. Is it possible to check if the response needs to be parsed before attempting it? Maybe it is possible to check the `Content-Type` in the header before parsing it, something like:
```

                let response

                const contentType = success.headers.get('Content-Type')

                if (contentType && contentType.includes('application/json')) {
                  try {
                    response = await success.json()
                  } catch (e) {
                    console.warn('Could not parse response. It might have already been parsed.', e);
                    response = success
                  }
                } else {
                  response = success
                }
```

2025-01-27 12:57 UTC, sakutademos commented on client/js/components/tags/TagsList.vue
> +        this.updateTagTopic({
I see there is a bug when updating the `TagTopic` with new relationships: the bug occurs only when trying to drag the tag from the topic below and there is no issue if I drag the tag from TagTopic nr.1 to TagTopc nr.2, but there is a bug (no relationships in the payload) when I try to drag the tag from TagTopic nr.2 to TagTopic  nr.1. This is a pattern that I have found, but do not yet understand where is the problem

2025-01-27 15:54 UTC, sakutademos commented on client/js/components/tags/TagsList.vue
> +        this.updateTagTopic({
ok, got it: the update action for the new `TagTopic` should happen after the update action for the old `TagTopic`. It makes sense because, after the new relationships are created, you remove them immediately

2025-01-28 11:14 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
> +            ['topic', 'procedure', 'id']
done in a380e6494c8a2dbb26e5fe404a56364def8922cc

2025-01-28 11:14 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/ResourceTypes/TagTopicResourceType.php
> +            ['procedure', 'id']
done in a380e6494c8a2dbb26e5fe404a56364def8922cc

2025-01-28 12:52 UTC, sakutademos commented on package.json
> +    "@demos-europe/demosplan-ui": "^0.3.44",
with the changes from the 0.3.44 version every object in the tree list (even thought it is a branch or a leaf) gets the `sortablelist__empty` class, which causes an issue --> i think the check `isBranch` have to be added here as well
![image](https://github.com/user-attachments/assets/327806eb-3cc0-499a-a47e-92533eaf7400)

2025-01-28 13:23 UTC, sakutademos commented on client/js/components/tags/TagListEditForm.vue
> +      <template  v-if="isInEditState !== nodeElement.id">
```suggestion
      <template v-if="isInEditState !== nodeElement.id">
```

2025-01-28 13:23 UTC, sakutademos commented on client/js/components/tags/TagListEditForm.vue
> +        }" />
some styling nitpick: i think we have to maintain a consistent code styling, so if you add an empty lines in this block, it has to be added below as well

```suggestion
    <template v-else>
      <div
        class="flex-1"
        v-text="nodeElement.attributes.title" />
      <div class="text-center w-9">
        <dp-contextual-help
          v-if="nodeElement.relationships?.boilerplate"
          icon="file"
          :text="nodeElement.relationships.boilerplate.attributes.title" />
      </div>
      <addon-wrapper
        hook-name="tag.edit.form"
        :addon-props="{
          tag: nodeElement
        }" />
```

2025-01-28 13:23 UTC, sakutademos commented on client/js/components/tags/TagListBulkControls.vue
> +      data-cy="deleteSelectedItems"
should we be more specific with the naming of `data-cy`, smth like `bulkControls:deleteSelectedItems`

2025-01-28 13:23 UTC, sakutademos commented on client/js/components/tags/TagsImportForm.vue
> +        <input type="hidden" name="r_importCsv" :value="this.uploadedCSV" />
sorry, this styling thing: the attributes on the new lines and empty lines

2025-01-30 08:17 UTC, sakutademos commented on package.json
> +    "@demos-europe/demosplan-ui": "^0.3.44",
was resolved in the dptreelistnode component

2025-01-30 12:55 UTC, sakutademos approved these changes
FE-Part looks lgtm!

2025-02-04 16:10 UTC, martendemos requested changes
Not finished yet, but so far enough for now.

2025-02-05 08:50 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Logic/RpcDeleteTags.php
> +                    $this->sendTagDeleteAddonNotification($tag->getId());
This does not work as the Tag cant be deleted if there are foreign keys still in use....
The addon relation needs to be deleted first..

2025-02-05 09:23 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
>       * @DplanPermissions("area_admin_statements_tag")
Otherwise the whole controller needs to be changed....
It would be nice - but a separate PR would make sense regarding its size already?

2025-02-05 09:32 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Logic/RpcDeleteTags.php
> +class RpcDeleteTags implements RpcMethodSolverInterface
Tags and Topics were able to be deleted in bulk.
Since this refactoring they are not anymore... but the BE provides this feature as it was build before.
The ResourceTypes only provide a single delete. And you would have to either request the TagTopic or Tag one depending on what entity you want to handle.

2025-02-05 10:01 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
> +        // todo need title and template for tag create
Thanks a lot!
These two routes are actually not used and were removed in 8dc60b5130214f7ae64d9e4cb9fc84f4e30a2f54

2025-02-05 10:02 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
> +        string $procedure,
also done in 8dc60b5130214f7ae64d9e4cb9fc84f4e30a2f54

2025-02-05 10:03 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
>       * @return RedirectResponse|Response
adjusted the return type hint for the route that still is in use - it will always redirect 8dc60b5130214f7ae64d9e4cb9fc84f4e30a2f54

2025-02-05 10:04 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
> +    #[Route(name: 'DemosPlan_statement_administration_tag_create', path: '/verfahren/{procedure}/schlagwort/erstellen', defaults: ['master' => false], options: ['expose' => true])]
8dc60b5130214f7ae64d9e4cb9fc84f4e30a2f54

2025-02-05 11:00 UTC, martendemos commented on demosplan/DemosPlanCoreBundle/Repository/TagTopicRepository.php
> +                $newProcedure->detachAllTopics();
ping

2025-02-05 13:39 UTC, martendemos requested changes

2025-02-05 13:39 UTC, martendemos commented on demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
> +            ->addUpdateBehavior(
This logic (implemented in the resourcetypes) are existing before?
If so, where was/is this logic located. I would try to compare it, cause this is pretty complex.

2025-02-05 17:39 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Logic/RpcDeleteTags.php
> +class RpcDeleteTags implements RpcMethodSolverInterface
still working on it - but first basic one done in 429cc73dc07a8403b6273eabad3f833b3675af8f

2025-02-05 17:39 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Logic/RpcDeleteTags.php
> +class RpcDeleteTags implements RpcMethodSolverInterface
done in 429cc73dc07a8403b6273eabad3f833b3675af8f

2025-02-05 17:57 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
> +        $records->rewind();
the first rewind should not be necessary. and got removed in 9c080351007ca6e4d3da281a53f6a44727be8fc9

The addon has to potentially read through the whole iterator to pick its relevant fields
than it has to rewind the iterator so that the core can then process the basic import fields like previously.

2025-02-05 18:04 UTC, MoritzMandler commented on demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
> +            ->addUpdateBehavior(
it did exist just for a get Request - and even there the old syntax was used...
The features the resourceTypes need to provide were previously found in demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php

2025-02-06 12:46 UTC, martendemos approved these changes
aside of missing tests: approved

2025-02-12 16:41 UTC, MoritzMandler commented
Test is outsourced into https://github.com/demos-europe/demosplan-core/pull/4331 as it is currently not in a working state.

2025-02-17 16:47 UTC, merged