Fix dubble ExternalId for synchronized statements
demos-europe/demosplan-core pull request #4176
Opened 2024-12-23 09:42 UTC by jalalifardemos

### Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-4237/STN-Nr-wird-doppelt-vergeben

Description: check existed statements external ID in target procedure to find same and if true then change it with '-1' and if false continue. And create a migration to fix old ones in EWM project 

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Create/Update tests
- [ ] Update documentation
- [ ] Add/Update data-cy attributes ([conventions](https://dplan-documentation.demos-europe.eu/development/guidelines-conventions/coding-styleguides/twig_html.html#guideline-for-naming-cypress-hooks))
- [ ] Run `yarn lint`
- [ ] Run `yarn test`
- [x] Link all relevant tickets
- [x] Move the tickets on the board accordingly
- [ ] Update changelog

2025-01-13 14:28 UTC, martendemos commented on demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
> +        foreach ($targetProcedureStatemnts as $targetProcedureStatemnt) {
typos in "Statemnts"

2025-01-13 14:34 UTC, martendemos requested changes
found at least one major issue

2025-01-14 08:23 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
> +                $newOriginalStatement->setExternId($sourceStatement->getExternId().'-1');
In which case can set a specific external ID?

2025-01-14 14:08 UTC, martendemos commented on demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
> +                $newOriginalStatement->setExternId($sourceStatement->getExternId().'-1');
in other words: what should happend, when a external ID occurs more than twice?
for example: a statement with the ID "1005" will be copied to the target-procedure.
Afterwards another Statement with the same ID will be copied to this target*-procedure.
This will lead to two Statements with the ID "1005-1", isn't it?
Is this intended?

2025-01-14 14:09 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
> +                $newOriginalStatement->setExternId($sourceStatement->getExternId().'-1');
done in https://github.com/demos-europe/demosplan-core/pull/4176/commits/b14f2b41a6302b52f8f18472bef7f79d5b80d9b0

2025-01-14 14:09 UTC, jalalifardemos commented on demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
> +        foreach ($targetProcedureStatemnts as $targetProcedureStatemnt) {
done in https://github.com/demos-europe/demosplan-core/pull/4176/commits/b14f2b41a6302b52f8f18472bef7f79d5b80d9b0

2025-01-14 14:22 UTC, martendemos requested changes
Okay I needed to check the context of this fix and as far as I understand, the actual issue is not located in this class, because the related ticket does not describe synchronization of statements from one procedure into another.
So the is the wrong place to try to fix the actual issue.

Please check the last reproducing description:
https://demoseurope.youtrack.cloud/issue/DPLAN-4237/STN-Nr-wird-doppelt-vergeben#focus=Comments-4-55341.0-0

2025-01-16 07:41 UTC, closed without merging