F 30480 custom default publication of documentcategories
demos-europe/demosplan-core pull request #546
Opened 2023-01-05 16:21 UTC by martendemos

**Ticket:** https://yaits.demos-deutschland.de/T30480

To cover different 
In order to reduce the effort on importing documents (ZIP-archive), it should be possible for the user to choose if all containing elements should be initially published or not.

### How to review/test
Import a ZIP-archive in the document section. While the uploading process, a kind of modal should be appear, where you can choose to publish or not.
All contained elements of the imported zip-archive should be in the selected state.

### PR Checklist

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Tests updated/created
- [ ] Update documentation
- [ ] Link all relevant tickets
- [ ] Move the tickets on the board accordingly

2023-01-09 10:55 UTC, martendemos commented
still pushing ....

2023-01-11 09:55 UTC, spiess-demos requested changes

2023-01-11 09:55 UTC, spiess-demos commented on templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/elements_admin_import.html.twig
> +                    :label="{ text: Translator.trans('element.state.autoswitch', { state: Translator.trans('published') }) }"
I find it confusing to (re-)use the already-existing translation key here. `element.state.autoswitch` carries a distinct meaning which does not apply to the current case. I'd rather suggest to add a new translation key `element.state.publish` or the like. To also differentiate what actually happens, i'd also suggest to chose " Kategorie  sofort veröffentlichen".

2023-01-11 09:55 UTC, spiess-demos commented on translations/messages+intl-icu.de.yml
> +element.state.autoswitch: "Status der Kategorie(n) automatisch auf \"{state}\" umstellen"
See above comment. I'd revert the change to `element.state.autoswitch` and add a new key instead.

2023-01-11 10:48 UTC, gruenbergerdemos commented
Concerns done in [8b5cd10](https://github.com/demos-europe/demosplan-core/pull/546/commits/8b5cd10fbb68d1a3be5710ebab9c5a716a169b6f)

2023-01-11 12:31 UTC, spiess-demos submitted a review, later dismissed
one last suggestion, otherwise lgtm!

2023-01-11 12:31 UTC, spiess-demos commented on templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/elements_admin_import.html.twig
> +                :label="{ text: Translator.trans('element.state.publish', { state: Translator.trans('published') }) }"
```suggestion
                :label="{ text: Translator.trans('element.state.publish') }"
```

2023-01-11 15:15 UTC, spiess-demos approved these changes
FE lgtm (code review).

2023-01-11 15:57 UTC, mussbach approved these changes
lgtm, code review only. Perhaps you could tackle the php 8 deprecation

2023-01-11 16:03 UTC, MoritzMandler requested changes
Just the one review-dog parameter-reorder thing...
appart from that code lgtm and worked well when tested

2023-01-11 16:03 UTC, MoritzMandler commented on demosplan/DemosPlanDocumentBundle/Logic/DocumentHandler.php
> +        array &$errorReport
please change the order of these parameters as review-dog points out.

2023-01-12 09:07 UTC, MoritzMandler approved these changes
Thank you - lgtm

2023-01-12 11:06 UTC, merged