bug(refs T27479): Fix bulk edit for documents
demos-europe/demosplan-core pull request #648
Opened 2023-01-18 16:10 UTC by gruenbergerdemos

**Ticket:** https://yaits.demos-deutschland.de/T27479

The given objects in the change event for node selection have changed (in DpTreeListNode), so they also need to be changed in the methods listening to that event. 
Also some refactoring.

### How to review/test
Go to Verfahren -> Dokumente and select some documents. There should be a bulk edit header appear, where you can delete or publish the documents.

2023-01-19 14:12 UTC, muellerdemos requested changes
When selecting single documents of the list, the control menu does indeed appear now, however there is still an problem with the bulk edit checkbox, which does not trigger the rendering of the control menu.

![image](https://user-images.githubusercontent.com/91727189/213464224-67b27e80-4cf7-4ce8-9c23-9f6175be9b84.png)

![image](https://user-images.githubusercontent.com/91727189/213464274-8bcf233e-60d1-426b-b1dd-09a412ec7376.png)

2023-01-19 14:24 UTC, gruenbergerdemos commented
This is another bug, it has the same cause as here https://yaits.demos-deutschland.de/T27441. Unfortunately I don't know how to fix this, so I didn't approach it here. If you have an idea, happy to hear, otherwise I think we should fix it another time.

2023-01-20 16:09 UTC, spiess-demos approved these changes
lgtm! code review only, seen it working at @muellerdemos ' machine.

2023-01-20 16:27 UTC, muellerdemos approved these changes
These changes are working and hence this PR can be merged. There is another PR https://github.com/demos-europe/demosplan-ui/pull/73 which fixes the underlying Problem

2023-01-20 16:28 UTC, merged