Feat T30254 more adjustments for addons
demos-europe/demosplan-core pull request #721
Opened 2023-01-31 10:59 UTC by bakridemos

Description: more related addons adjustements

2023-02-01 12:39 UTC, AlexMenschoid reviewed
@graupnerdemos The CS Fixer is mean to me! I don't want to play CS Fixer ping-pong, that sounds like a very cruel form of developer hell....

@bakridemos otherwise the PR looks good, I just need to have the CS Fixer thing cleared, then I'll approve it.

2023-02-01 12:39 UTC, AlexMenschoid commented on demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
>       * @DplanPermissions("area_admin_paragraphed_document")
@graupnerdemos Why is the CS-fixer now adding the empty line I wished for but couldn't get in the other PR?!

2023-02-01 12:39 UTC, AlexMenschoid commented on demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
> +     *
@graupnerdemos And why is the CS Fixer in turn ripping these definitions apart?!

2023-02-16 08:11 UTC, dresslerdemos requested changes

2023-02-16 08:11 UTC, dresslerdemos commented on demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
> +        return array_filter($assetList, fn (array $assetInfo) => 0 !== count($assetInfo));
```suggestion

        // avoid exposing addon information unnecessarily
        return array_filter($assetList, fn (array $assetInfo) => 0 !== count($assetInfo));
```

2023-02-20 05:52 UTC, bakridemos commented on demosplan/DemosPlanCoreBundle/Event/Procedure/PostNewProcedureCreatedEvent.php
> +    }
done in https://github.com/demos-europe/demosplan-core/pull/721/commits/afd2690b8e57e1fec2e2affc52deb89c4d780822

2023-02-20 12:44 UTC, dresslerdemos approved these changes

2023-02-20 14:29 UTC, dresslerdemos approved these changes

2023-02-21 10:36 UTC, merged